apiVersion: v1
kind: Service
metadata:
  name: {{ include "iperf3-monitor.fullname" . }}-exporter-svc
  labels:
    {{- include "iperf3-monitor.labels" . | nindent 4 }}
    app.kubernetes.io/component: exporter
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "iperf3-monitor.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: exporter
  ports:
    - name: metrics
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP